bag/urls.py
"""Urls for the bag app."""
from django.urls import path
from .views import (
    BagDisplayView,
    AddToBagAJAXView,
    RemoveUnitFromBagAJAXView,
    AddUnitToBagAJAXView,
    RemoveAllItemUnitsFromBagAJAXView,
    RemoveAllBagAJAXView,
    PromoCodeAJAXView,
)


urlpatterns = [
    path('bag_display/', BagDisplayView.as_view(), name='bag_display'),
    path(
        'add_to_bag/',
        AddToBagAJAXView.as_view(),
        name='add_to_bag'
    ),
    path(
        'remove_unit_from_bag/',
        RemoveUnitFromBagAJAXView.as_view(),
        name='remove_unit_from_bag'
    ),
    path(
        'add_unit_to_bag/',
        AddUnitToBagAJAXView.as_view(),
        name='add_unit_to_bag'
    ),
    path(
        'remove_all_item_units_from_bag/',
        RemoveAllItemUnitsFromBagAJAXView.as_view(),
        name='remove_all_item_units_from_bag'
    ),
    path(
        'remove_all_bag/',
        RemoveAllBagAJAXView.as_view(),
        name='remove_all_bag'
    ),
    path(
        'apply_promo_code/',
        PromoCodeAJAXView.as_view(),
        name='apply_promo_code'
    ),
]

ecommerce_project/urls.py
"""ecommerce_project URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from .views import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('profiles/', include('profiles.urls')),
    path('inventory/', include('inventory.urls')),
    path('bag/', include('bag.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('promotions/', include('promotions.urls')),
    path('email_notifications/', include('email_notifications.urls')),
    path('personnel/', include('personnel.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('reviews/', include('reviews.urls')),
]

handler404 = 'ecommerce_project.views.handler404'
handler500 = 'ecommerce_project.views.handler500'

promotions/urls.py
"""URLs for the promotion app."""
from django.urls import path
from .views import (
    PromotionsListView,
    AddPromotionView,
    EditPromotionView,
    DeletePromotionAJAXView,
)


urlpatterns = [
    path(
        'promotions_list/',
        PromotionsListView.as_view(),
        name='promotions_list'
    ),
    path(
        'add_promotion/',
        AddPromotionView.as_view(),
        name='add_promotion'
    ),
    path(
        'edit_promotion/<int:pk>/',
        EditPromotionView.as_view(),
        name='edit_promotion'
    ),
    path(
        'delete_promotion/',
        DeletePromotionAJAXView.as_view(),
        name='delete_promotion'
    ),
]

promotions/models.py
"""Models for the promotions app."""
from django.db import models
from django.utils import timezone
from datetime import datetime
from datetime import timedelta
from decimal import Decimal
from django.utils.text import slugify
from django.core.validators import MinValueValidator, MaxValueValidator
from inventory.models import ProductInventory

PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]


class Promotion(models.Model):
    """Model for promotions."""
    name = models.CharField(
        max_length=100,
        unique=True,
        blank=False,
        null=False,
        verbose_name='Name',
        help_text='Name of the promotion.'
    )
    slug = models.SlugField(
        max_length=100,
        unique=True,
        blank=False,
        null=False,
        verbose_name='Slug',
        help_text='Slug of the promotion.'
    )
    description = models.TextField(
        max_length=700,
        null=False,
        blank=False,
        verbose_name='Promotion description',
        help_text='format: required, max_length=700'
    )
    promotion_code = models.CharField(
        max_length=100,
        unique=True,
        blank=False,
        null=False,
        verbose_name='Promotion code',
        help_text='Promotion code.'
    )
    promotion_reduction = models.DecimalField(
        max_digits=3,
        decimal_places=0,
        default=Decimal(0),
        validators=PERCENTAGE_VALIDATOR,
    )
    active = models.BooleanField(default=True)
    start_date = models.DateTimeField(
        verbose_name='Start date',
    )
    end_date = models.DateTimeField(
        verbose_name='End date',
    )
    products_inventory_in_promotion = models.ManyToManyField(
        ProductInventory,
        blank=True,
        related_name='products_promotions',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Created at',
        help_text='Date and time of creation.'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Updated at',
        help_text='Date and time of last update.'
    )

    class Meta:
        """Meta class for promotions."""
        verbose_name = 'Promotion'
        verbose_name_plural = 'Promotions'
        ordering = ['-created_at']

    def __str__(self):
        """Return the name of the promotion."""
        return self.name

    def save(self, *args, **kwargs):
        """Save the promotion."""
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_promotion_code(self):
        """Return the promotion code."""
        return self.promotion_code

    def is_active_now(self):
        """Return whether the promotion is active now."""
        start_date = self.start_date.replace(tzinfo=None)
        end_date = self.end_date.replace(tzinfo=None)
        return (
            self.active and start_date < datetime.now() < end_date
        )

    def is_active_soon(self):
        """Return whether the promotion is active soon."""
        start_date = self.start_date.replace(tzinfo=None)
        end_date = self.end_date.replace(tzinfo=None)
        return (
            self.active and start_date < datetime.now() + timedelta(
                days=7
            ) < end_date
        )

    def get_products_in_promotion(self):
        """Return the products in the promotion."""
        return self.products_inventory_in_promotion.all()

promotions/forms.py
"""Forms for the promotions app."""
from django import forms
from .models import Promotion


class PromotionForm(forms.ModelForm):
    """Form for the Promotion model."""
    class Meta:
        model = Promotion
        fields = [
            'name',
            'description',
            'promotion_code',
            'promotion_reduction',
            'start_date',
            'end_date',
            'products_inventory_in_promotion',
            'active',
        ]
        promotion_reduction = forms.DecimalField()
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Name',
                    'title': 'Promotion Name',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Description',
                    'title': 'Promotion Description',
                }
            ),
            'promotion_code': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Promotion Code',
                    'title': 'Promotion Code',
                }
            ),
            'active': forms.CheckboxInput(
                attrs={
                    'class': 'form-control',
                    'title': 'Promotion Active',
                }
            ),
            'start_date': forms.DateTimeInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Start Date',
                    'title': 'Promotion Start Date',
                }
            ),
            'end_date': forms.DateTimeInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'End Date',
                    'title': 'Promotion End Date',
                }
            ),
            'products_inventory_in_promotion': forms.SelectMultiple(
                attrs={
                    'class': 'form-control',
                    'title': 'Select products inventory in promotion',
                    'multiple': 'multiple',
                }
            ),
        }

promotions/views.py
"""Views for the promotions app."""
from django.views import View
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.paginator import Paginator
from .models import Promotion
from .forms import PromotionForm


class PromotionsListView(View):
    """View for the promotions list page."""
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # Check if user is a admin
            if request.user.profile.role.id == 1:
                return render(
                    request,
                    'profiles/access_denied.html',
                )
            else:
                p = Paginator(Promotion.objects.all(), 10)
                page = request.GET.get('page')
                promotions = p.get_page(page)
                context = {
                    'promotions': promotions,
                }
                return render(
                    request,
                    'promotions/promotions_list.html',
                    context
                )
        else:
            return render(
                request,
                'account/login.html',
            )


class AddPromotionView(View):
    """View for the add promotion page."""
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # Check if user is a admin
            if request.user.profile.role.id == 3:
                form = PromotionForm(request.POST)
                return render(
                    request,
                    'promotions/add_promotion.html',
                    {'form': form}
                )
            else:
                return render(
                    request,
                    'profiles/access_denied.html',
                )
        else:
            return render(
                request,
                'account/login.html',
            )

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # Check if user is a admin
            if request.user.profile.role.id == 3:
                form = PromotionForm(request.POST)
                if form.is_valid():
                    promotion = form.save(commit=False)
                    products_inventory_in_promotion = form.cleaned_data[
                        'products_inventory_in_promotion'
                    ]
                    promotion.save()
                    # Add the product inventories to the promotion
                    promotion.products_inventory_in_promotion.set(
                        products_inventory_in_promotion
                    )
                    promotion.save()
                    return redirect('promotions_list')
                else:
                    return render(
                        request,
                        'promotions/add_promotion.html',
                        {'form': form}
                    )
            else:
                return render(
                    request,
                    'profiles/access_denied.html',
                )
        else:
            return render(
                request,
                'account/login.html',
            )


class EditPromotionView(View):
    """View for the edit promotion page."""
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # Check if user is a admin
            if request.user.profile.role.id == 3:
                promotion = Promotion.objects.get(id=kwargs['pk'])
                form = PromotionForm(instance=promotion)
                return render(
                    request,
                    'promotions/edit_promotion.html',
                    {'form': form, 'promotion': promotion}
                )
            else:
                return render(
                    request,
                    'profiles/access_denied.html',
                )
        else:
            return render(
                request,
                'account/login.html',
            )

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # Check if user is a admin
            if request.user.profile.role.id == 3:
                promotion = Promotion.objects.get(id=kwargs['pk'])
                form = PromotionForm(request.POST, instance=promotion)
                if form.is_valid():
                    promotion = form.save(commit=False)
                    products_inventory_in_promotion = form.cleaned_data[
                        'products_inventory_in_promotion'
                    ]
                    promotion.save()
                    # Add set of product inventories to promotion
                    promotion.products_inventory_in_promotion.set(
                        products_inventory_in_promotion
                    )
                    promotion.save()
                    return redirect('promotions_list')
                else:
                    return render(
                        request,
                        'promotions/edit_promotion.html',
                        {'form': form, 'promotion': promotion}
                    )
            else:
                return render(
                    request,
                    'profiles/access_denied.html',
                )
        else:
            return render(
                request,
                'account/login.html',
            )


class DeletePromotionAJAXView(View):
    """View for the delete promotion AJAX."""
    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # Check if user is a admin
            if request.user.profile.role.id == 3:
                if request.is_ajax() and request.user.profile.role.id == 3:
                    promotion_id = request.POST.get('promotion_id')
                    promotion = Promotion.objects.get(id=promotion_id)
                    promotion.delete()
                    return JsonResponse({'success': True})
                return JsonResponse({'success': False})
            else:
                return render(
                    request,
                    'profiles/access_denied.html',
                )
        else:
            return render(
                request,
                'account/login.html',
            )

promotions/templates/promotions/add_promotion.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Add Promo{% endblock %}

{% block content %}
  <div class="dashboard">
    {% comment %} Limit access for customers {% endcomment %}
    {% if request.user.is_authenticated and not request.user.profile.role.id == 1 %}
      <form method="POST" class="dashboard__form promo__form">
        <h1 class="dashboard__main--name">Add Promotion</h1>
        {% csrf_token %}
        {% for field in form %}
          {% if field.is_hidden %}
            {{ field }}
          {% else %}
            {{ field.label_tag }}
            {{ field }}
          {% endif %}
        {% endfor %}
        {% comment %} Form buttons {% endcomment %}
        <div class="form__btns accent">
          <a href="{% url 'promotions_list' %}" aria-label="Go to Promotions page" class="btn btn__cancel">
            <i class="fas fa-arrow-circle-left"></i>
            Cancel
          </a>
          <button type="submit" class="btn btn__add">
            <i class="fa fa-plus-circle"></i>
            Add Promotion
          </button>
        </div>
      </form>
    {% else %}
      <div class="dashboard__main">
        <h1>You are not authorized to access this page</h1>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block postloadjs_extra %}
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function () {
      $(function () {
        $('#id_active').checkboxradio();
      });
      // add break before label for="is_active"
      $('label[for="id_active"]').before('<br>');
      //add bread after input="is_active"
      $('#id_active').after('<br>');
      //remove form control from input "is_active" to prevent overflow
      $('#id_active').removeClass('form-control');
      $('#id_start_date').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd',
      });
      $('#id_end_date').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd',
      });
      $('#id_products_inventory_in_promotion').select2(
        {
          placeholder: "Select a sku",
          allowClear: true,
        }
      );
    });
  </script>
{% endblock %}

promotions/templates/promotions/edit_promotion.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Edit Promo{% endblock %}

{% block content %}
  <div class="dashboard">
    {% comment %} Limit access for customers {% endcomment %}
    {% if request.user.is_authenticated and not request.user.profile.role.id == 1 %}
      <form method="POST" class="dashboard__form promo__form">
        <h1 class="dashboard__main--name">Edit Promotion</h1>
        {% csrf_token %}
        {% for field in form %}
          {% if field.is_hidden %}
            {{ field }}
          {% else %}
            {{ field.label_tag }}
            {{ field }}
          {% endif %}
        {% endfor %}
        {% comment %} Form buttons {% endcomment %}
        <div class="form__btns accent">
          <a href="{% url 'promotions_list' %}" aria-label="Go to Promotions page" class="btn btn__cancel">
            <i class="fas fa-arrow-circle-left"></i>
            Cancel
          </a>
        <button type="submit" class="btn btn__add">
          <i class="fas fa-save"></i>
          Save Changes
        </button>
      </div>
    </form>
    {% else %}
      <div class="dashboard__main">
        <h1>You are not authorized to access this page</h1>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block postloadjs_extra %}
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function () {
      $(function () {
        $('#id_active').checkboxradio();
      });
      // add break before label for="is_active"
      $('label[for="id_active"]').before('<br>');
      //add bread after input="is_active"
      $('#id_active').after('<br>');
      //remove form control from input "is_active" to prevent overflow
      $('#id_active').removeClass('form-control');
      $('#id_start_date').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd',
      });
      $('#id_end_date').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd',
      });
      $('#id_products_inventory_in_promotion').select2(
        {
          placeholder: "Select a sku",
          allowClear: true,
        }
      );
    });
  </script>
{% endblock %}

promotions/templates/promotions/promotions_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <style>
    .content__container {
      justify-content: start !important;
      align-items: flex-start !important;
    }
    .btn__small {
      font-size: 0.9rem;
      padding: 0.2em 0.5rem;
    }
  </style>
{% endblock %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}All Promos{% endblock %}

{% block content %}
  <div class="promotions">
  {% comment %} Limit access for customers {% endcomment %}
  {% if request.user.is_authenticated and not request.user.profile.role.id == 1 %}
    <section class="promotion__header">
      <h1 class="dashboard__main--name" >Promotions</h1>
      {% comment %} Accessable only to Admin {% endcomment %}
      {% if request.user.profile.role.id == 3 %}
        <div class="promotions__add">
          <a href="{% url 'add_promotion' %}" class="btn btn-primary btn__add promotions__add--btn" aria-label="Add promotion">
            <i class="fa fa-plus-circle"></i>
            Add Promotion
          </a>
        </div>
      {% endif %}
    </section>
    {% comment %} If there are any promotions {% endcomment %}
    {% if promotions %}
    {% comment %} Promotions table {% endcomment %}
      <div class="promotions__table">
        <div class="promotion title">
          <strong class="promotion__title--name">Name</strong>
          <strong>Now</strong>
          <strong>Start</strong>
          <strong>End</strong>
          <strong>Active</strong>
          <strong>Code</strong>
        </div>
        {% comment %} Get all promotions {% endcomment %}
        {% for promotion in promotions %}
          <section class="promotion cell" data-id="{{ promotion.id }}">
            <h2 class="promotion__title">{{ promotion.name }}</h2>
            <p class="promotion__now">
              {% if promotion.is_active_now %}
                <i class="fa fa-check-circle"></i>
              {% else %}
                <i class="fa fa-times-circle"></i>
              {% endif %}
            </p>
            <p class="promotion__date--start">{{ promotion.start_date|date:"d.m.Y" }}</p>
            <p class="promotion__date--end">{{ promotion.end_date|date:"d.m.Y" }}</p>
            <p class="promotion__status">
              {% if promotion.active %}
                <i class="fa fa-check-circle"></i>
              {% else %}
                <i class="fa fa-times-circle"></i>
              {% endif %}
            </p>
            <p class="promotion__code">{{ promotion.promotion_code }}</p>
            <div class="promotion__products hidden">
              {% comment %} Accessable only to Admin {% endcomment %}
              <div class="promotion__products--list">
                {% if request.user.profile.role.id == 3 %}
                  <div class="promotion__btns">
                    <a href="{% url 'edit_promotion' pk=promotion.id %}" class="btn btn__edit btn__small" aria-label="Edit promotion">
                      <i class="fa fa-pencil"></i>
                      Edit
                    </a>
                    <button type="button" class="btn btn__delete btn__small" data-bs-toggle="modal" data-bs-target="#exampleModal" data-delete="{{ promotion.id }}">
                      <i class="fa fa-trash"></i>
                      Delete
                    </button>
                  </div>
                {% endif %}
                {% comment %} Units in promotions {% endcomment %}
                {% if promotion.products_inventory_in_promotion.all %}
                  {% for product_inventory in promotion.products_inventory_in_promotion.all %}
                    <a class="promotion__product" data-attr="{{ product_inventory.id }}"
                        href="{% url 'product_inventory_details' pk=product_inventory.product.pk inventory_pk=product_inventory.id %}"
                        aria-label="Go to product inventories details">
                      <strong>{{ product_inventory.sku }}</strong>
                      <div>{{ product_inventory.product.name }}</div>
                      {% if product_inventory.attribute_values %}
                        {% for value in product_inventory.get_attribute_values %}
                          <strong>{{ value.attribute_value }}</strong>
                        {% endfor %}
                      {% endif %}
                      <i class="fa fa-external-link" aria-hidden="true"></i>
                    </a>
                  {% endfor %}
                {% else %}
                  <p class="promotion__products empty">No products in this promotion</p>
                {% endif %}
              </div>
            </div>
          </section>
        {% endfor %}
        {% comment %} Control Pagination {% endcomment %}
        {% if promotions.paginator.num_pages %}
          {% if not promotions.paginator.num_pages == 1 %}
            <div class="pagination">
              <div class="pagination__navigation">
                {% if promotions.has_previous and not promotions.has_next %}
                  <a href="?page={{ promotions.previous_page_number }}" class="pagination__navigation--btn"
                    aria-label="Go to previous page results">
                    <i class="fas fa-chevron-left"></i>
                  </a>
                  <div class="pagination__navigation--fake">
                    <i class="fas fa-chevron-right"></i>
                  </div>
                {% elif promotions.has_next and not promotions.has_previous %}
                  <div class="pagination__navigation--fake">
                    <i class="fas fa-chevron-left"></i>
                  </div>
                  <a href="?page={{ promotions.next_page_number }}" class="pagination__navigation--btn"
                    aria-label="Go to next page results">
                    <i class="fas fa-chevron-right"></i>
                  </a>
                {% elif promotions.has_next and promotions.has_previous %}
                  <a href="?page={{ promotions.previous_page_number }}" class="pagination__navigation--btn"
                    aria-label="Go to previous page results">
                    <i class="fas fa-chevron-left"></i>
                  </a>
                  <a href="?page={{ promotions.next_page_number }}" class="pagination__navigation--btn"
                    aria-label="Go to next page results">
                    <i class="fas fa-chevron-right"></i>
                  </a>
                {% else %}
                  <div class="pagination__navigation--fake">
                    <i class="fas fa-chevron-left"></i>
                  </div>
                  <div class="pagination__navigation--fake">
                    <i class="fas fa-chevron-right"></i>
                  </div>
                {% endif %}
              </div>
              <div class="pagination__location">
                Page <span>{{ promotions.number }}</span> of {{ promotions.paginator.num_pages }}
              </div>
            </div>
          {% endif %}
        {% endif %}
      </div>
    {% else %}
      <div class="">
        <strong>No promotions found.</strong>
      </div>
    {% endif %}
  {% endif %}
  {% comment %} Modal for promo deletion {% endcomment %}
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Promo</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this promotion?
        </div>
        <div class="modal-footer form__btns accent">
          <button type="button" class="btn btn__cancel" data-bs-dismiss="modal">
            <i class="fas fa-arrow-circle-left"></i>
            Cancel
          </button>
          <button type="button" class="btn btn__delete confirm__delete" >
            <i class="fas fa-save"></i>
            Delete
          </button>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

{% block postloadjs_extra %}
  <script>
    $(document).ready(function(){
      $('.promotion').each(function(){
        let promotion = $(this);
        let promotionId = promotion.data('id');
        console.log(promotionId);
        // close modal reusable function
        promotion.on('click', function(){
          // find .promotion__products for this
          let products = promotion.find('.promotion__products');
          if(products.hasClass('hidden')){
            products.removeClass('hidden');
            // find delete button by data-delete="{{ promotion.id }}"
            let deleteBtn = promotion.find('[data-delete="' + promotionId + '"]');
            console.log(deleteBtn);
            // find .confirm__delete from #exampleModal
            let confirmDelete = $('#exampleModal').find('.confirm__delete');
            console.log('confirmDelete', confirmDelete);
            deleteBtnDataDelete = deleteBtn.data('delete');
            console.log('deleteBtnDataDelete', deleteBtnDataDelete);
            //add data-id attribute to confirmDelete
            confirmDelete.attr('data-id', deleteBtnDataDelete);
          } else {
            products.addClass('hidden');
          }
        });
      });
      // delete promotion
      $('.confirm__delete').on('click', function(){
        let promotionId = $(this).data('id');
        $.ajax({
          url: "{% url 'delete_promotion' %}",
          type: 'POST',
          data: {
            'promotion_id': promotionId,
            'csrfmiddlewaretoken': '{{ csrf_token }}'
          },
          success: function(data){
            // close modal
            $('#exampleModal').modal('hide');
            // remove promotion from page
            $('.promotion[data-id="' + promotionId + '"]').remove();
          },
          error: function(data){
            $('#messages-notes').remove();
            $('.bag').before('<div class="message-container" id="messages-notes">' +
              '<div class="message-container__message">' +
              '<p class="message-container__message--text">Something went wrong</p>' +
              '</div>' +
              '</div>');
            // remove the message block after 3 seconds
            setTimeout(() => {
              $('#messages-notes').remove();
            }, 3000);
          }
        });
      });
    });
  </script>
{% endblock %}