bag/urls.py
"""Urls for the bag app."""
from django.urls import path
from .views import (
    BagDisplayView,
    AddToBagAJAXView,
    RemoveUnitFromBagAJAXView,
    AddUnitToBagAJAXView,
    RemoveAllItemUnitsFromBagAJAXView,
    RemoveAllBagAJAXView,
    PromoCodeAJAXView,
)


urlpatterns = [
    path('bag_display/', BagDisplayView.as_view(), name='bag_display'),
    path(
        'add_to_bag/',
        AddToBagAJAXView.as_view(),
        name='add_to_bag'
    ),
    path(
        'remove_unit_from_bag/',
        RemoveUnitFromBagAJAXView.as_view(),
        name='remove_unit_from_bag'
    ),
    path(
        'add_unit_to_bag/',
        AddUnitToBagAJAXView.as_view(),
        name='add_unit_to_bag'
    ),
    path(
        'remove_all_item_units_from_bag/',
        RemoveAllItemUnitsFromBagAJAXView.as_view(),
        name='remove_all_item_units_from_bag'
    ),
    path(
        'remove_all_bag/',
        RemoveAllBagAJAXView.as_view(),
        name='remove_all_bag'
    ),
    path(
        'apply_promo_code/',
        PromoCodeAJAXView.as_view(),
        name='apply_promo_code'
    ),
]

ecommerce_project/urls.py
"""ecommerce_project URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from .views import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('profiles/', include('profiles.urls')),
    path('inventory/', include('inventory.urls')),
    path('bag/', include('bag.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('promotions/', include('promotions.urls')),
    path('email_notifications/', include('email_notifications.urls')),
    path('personnel/', include('personnel.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('reviews/', include('reviews.urls')),
]

handler404 = 'ecommerce_project.views.handler404'
handler500 = 'ecommerce_project.views.handler500'

profiles/urls.py
"""Urls for the profile app."""
from django.urls import path
from .views import (
    UserProfileView,
    EditAvatarAjaxView,
    ResetAvatarView,
    EditUserProfileView,
    DeleteProfileView,
    AddressesView,
    AddAddressView,
    EditAddressView,
    DeleteAddressView,
    ChangePrimaryAddressView,
)

urlpatterns = [
    path(
        'my_profile/edit_avatar/',
        EditAvatarAjaxView.as_view(),
        name='edit_avatar_ajax'
    ),
    path(
        'my_profile/reset_avatar/',
        ResetAvatarView.as_view(),
        name='reset-avatar'
    ),
    path(
        'delete_profile',
        DeleteProfileView.as_view(),
        name='delete_profile'
    ),
    path(
        '<str:user>/',
        UserProfileView.as_view(),
        name='my_profile'
    ),
    path(
        '<str:user>/edit/',
        EditUserProfileView.as_view(),
        name='edit_profile'
    ),
    path(
        '<str:user>/addresses/',
        AddressesView.as_view(),
        name='my_addresses'
    ),
    path(
        '<str:user>/addresses/add/',
        AddAddressView.as_view(),
        name='add_address'
    ),
    path(
        '<str:user>/addresses/<int:pk>/edit/',
        EditAddressView.as_view(),
        name='edit_address'
    ),
    path(
        '<str:user>/addresses/<int:pk>/delete/',
        DeleteAddressView.as_view(),
        name='delete_address'
    ),
    path(
        'my_addresses/set_primary',
        ChangePrimaryAddressView.as_view(),
        name='set_primary_address'
    ),
]

profiles/models.py
"""Models for the profiles app."""
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from datetime import date


class Role(models.Model):
    """Model for the roles."""
    name = models.CharField(
        max_length=50,
        unique=True,
        blank=False,
        null=False,
        verbose_name='Role name',
        help_text=(
            'format: required, max_length=50, unique=True, blank=False'
        )
    )
    description = models.TextField(
        max_length=500,
        blank=True,
        null=True,
        verbose_name='Role description',
        help_text=(
            'format: not required, max_length=500'
        )
    )

    def __str__(self):
        """Return the name of the role."""
        return self.name


class Profile(models.Model):
    """Model for the profiles."""
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
        verbose_name='User',
        help_text=(
            'format: required, unique=True'
        )
    )
    first_name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='First name',
        help_text=(
            'format: not required, max_length=50'
        )
    )
    last_name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Last name',
        help_text=(
            'format: not required, max_length=50'
        )
    )
    birthday = models.DateField(
        blank=True,
        null=True,
        verbose_name='Birthday',
        help_text=(
            'format: not required'
        )
    )
    avatar = CloudinaryField(
        'avatar',
        folder='avatars',
        blank=True,
        null=True,
    )
    subscription = models.BooleanField(
        default=False,
        verbose_name='Subscription',
        help_text=(
            'format: not required'
        )
    )
    role = models.ForeignKey(
        Role,
        on_delete=models.SET_NULL,
        null=True,
        default=1,
        verbose_name='Role',
        help_text=(
            'format: not required'
        )
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Created at',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Updated at',
    )

    def __str__(self):
        if self.first_name and self.last_name:
            return f'{self.first_name} {self.last_name}'
        if self.first_name:
            return self.first_name
        return self.user.username

    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        return '/static/images/default_avatar.svg'

    @property
    def age(self):
        if self.birthday:
            today = date.today()
            birthday = (
                today.year -
                self.birthday.year -
                (
                    (today.month, today.day) < (
                        self.birthday.month, self.birthday.day
                    )
                )
            )
            if birthday < 0:
                return 'Invalid birthday'
            return birthday
        return None


class Address(models.Model):
    """Model for the addresses."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='addresses',
        verbose_name='User',
        help_text=(
            'format: required'
        )
    )
    country = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        verbose_name='Country',
        help_text=(
            'format: required, max_length=50'
        )
    )
    county_region = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        verbose_name='County/region',
        help_text=(
            'format: required, max_length=50'
        )
    )
    city = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        verbose_name='City',
        help_text=(
            'format: required, max_length=50'
        )
    )
    address_line = models.CharField(
        max_length=150,
        blank=False,
        null=False,
        verbose_name='Address line',
        help_text=(
            'format: required, max_length=150'
        )
    )
    zip_code = models.CharField(
        max_length=10,
        blank=False,
        null=False,
        verbose_name='Zip code',
        help_text=(
            'format: required, max_length=10'
        )
    )
    phone_number = models.CharField(
        max_length=15,
        blank=False,
        null=False,
        verbose_name='Phone',
        help_text=(
            'format: required, max_length=15'
        )
    )
    is_primary = models.BooleanField(
        default=False,
        verbose_name='Is primary',
        help_text=(
            'format: not required'
        )
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Created at',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Updated at',
    )

    def __str__(self):
        """Return the address line."""
        return f'{self.user.username} - {self.zip_code} - {self.is_primary}'

    def save(self, *args, **kwargs):
        """Check if there is a primary address."""
        super().save(*args, **kwargs)
        if self.is_primary:
            for address in self.user.addresses.all().exclude(id=self.id):
                address.is_primary = False
                address.save()

profiles/forms.py
"""Forms for the profiles app."""
from django import forms
from .models import Profile, Address


class ProfileForm(forms.ModelForm):
    """Form for the Profile model."""
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'birthday', 'subscription']
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'title': 'max_length=50',
                    'placeholder': 'First name',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'title': 'max_length=50',
                    'placeholder': 'Last name',
                }
            ),
            'birthday': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'title': 'YYYY-MM-DD',
                    'placeholder': 'Birthday',
                }
            ),
            'subscription': forms.CheckboxInput(
                attrs={'class': 'form-check-input'}
            )
        }


class AddressForm(forms.ModelForm):
    """Form for the Address model."""
    class Meta:
        model = Address
        fields = [
            'country',
            'county_region',
            'city',
            'address_line',
            'zip_code',
            'phone_number',
            'is_primary'
        ]
        widgets = {
            'country': forms.Select(
                attrs={'class': 'form-control'},
            ),
            'county_region': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
            'address_line': forms.TextInput(attrs={'class': 'form-control'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'is_primary': forms.CheckboxInput(
                attrs={'class': 'form-check-input'}
            )
        }

    def __init__(self, *args, **kwargs):
            super(AddressForm, self).__init__(*args, **kwargs)
            self.fields['country'].widget.attrs.pop('maxlength', None)
            self.fields['county_region'].widget.attrs.pop('maxlength', None)
            self.fields['city'].widget.attrs.pop('maxlength', None)
            self.fields['address_line'].widget.attrs.pop('maxlength', None)
            self.fields['phone_number'].widget.attrs.pop('maxlength', None)

profiles/templates/profiles/access_denied.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <style>
  .dashboard__form.form__delete {
    max-width: 25rem;
    text-align: center;
    margin-top: 4em;
  }
  </style>
{% endblock %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Access Error{% endblock %}

{% block content %}
  <div class="dashboard">
    <div class="dashboard__form form__delete">
      <h1 class="dashboard__main--name">Access denied</h1>
      <div class="access__image">
        <img src="{% static 'images/access_denied.png' %}" alt="Access denied warning image">
      </div>
      <strong>You do not have permission to access this page.</strong>
    </div>
  </div>
{% endblock %}

profiles/templates/profiles/add_address.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Add Address{% endblock %}

{% block content %}
  <div class="profile">
    <div class="profile__section">
      {% comment %} Address form {% endcomment %}
      <form class="dashboard__form address__form" method="post" action="{% url 'add_address' user=request.user %}">
        <h1>Add Address</h1>
        {% csrf_token %}
        {{ address_form.as_p }}
        {% comment %} Form control buttons {% endcomment %}
        <div class="form__btns accent">
          <a href="{% url 'my_addresses' user=request.user %}" aria-label="Go to addresses details"
            class="btn btn-primary btn__cancel">
            <i class="fas fa-arrow-circle-left"></i>
            Cancel
          </a>
          <button class="btn__save btn" id="save-address-btn" type="submit">
            <i class="fas fa-save"></i>
            Save
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

{% block postloadjs_extra %}
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function () {
      let user_country = '{{ user.address.country }}';
      let user_county_region = '{{ user.address.county_region }}';
      let user_city = '{{ user.address.city }}';
      $('#id_country').select2(
        {
          placeholder: "Select a country",
          allowClear: true,
        }
      );
      $('#id_county_region').select2(
        {
          placeholder: "Select a county or region",
          allowClear: true,
        }
      );
      $('#id_city').select2(
        {
          placeholder: "Select a city",
          allowClear: true,
        }
      );
      $('#id_country').on('select2:open', function () {
        $('body').css('overflow-x', 'hidden');
      });
      $('#id_city').on('select2:open', function () {
        $('body').css('overflow-x', 'hidden');
      });
      $('#id_county_region').on('select2:open', function () {
        $('body').css('overflow-x', 'hidden');
      });
      $('#id_country').on('select2:close', function () {
        $('body').css('overflow-x', 'auto');
      });
      $('#id_county_region').on('select2:close', function () {
        $('body').css('overflow-x', 'auto');
      });
      $('#id_city').on('select2:close', function () {
        $('body').css('overflow-x', 'auto');
      });
      // need to fetch only country names from geonames.org
      $.ajax({
        url: 'https://secure.geonames.org/countryInfoJSON?username=juliia55',
        type: 'GET',
        dataType: 'json',
        success: function (data) {
          let select = $('#id_country');
          for (var i = 0; i < data.geonames.length; i++) {
            select.append($('<option>', {
              value: data.geonames[i].countryName,
              text: data.geonames[i].countryName,
              data: {
                code: data.geonames[i].countryCode,
                id: data.geonames[i].geonameId,
              }
            }));
          }
        }
      });
      $('#id_country').on('change', () => {
        let countryId = $('#id_country').find(':selected').data('id');
        $.ajax({
          url: 'https://secure.geonames.org/childrenJSON?geonameId=' + countryId + '&username=juliia55',
          type: 'GET',
          dataType: 'json',
          success: function (data) {
            let select = $('#id_county_region');
            select.empty();
            select.append($('<option>', {
              value: '',
              text: 'Select a county or region',
              data: {
                code: '',
                id: '',
              }
            }));
            for (var i = 0; i < data.geonames.length; i++) {
              select.append($('<option>', {
                value: data.geonames[i].name,
                text: data.geonames[i].name,
                data: {
                  code: data.geonames[i].countryCode,
                  id: data.geonames[i].geonameId,
                }
              }));
            }
            // select user's county or region by default
            $('#id_county_region').val(user_county_region).trigger('change');
          }
        });
      });
      $('#id_county_region').on('change', () => {
        let stateName = $('#id_county_region').find(':selected').text();
        let stateNameFirstWord = stateName.split(' ')[0];
        const city = $('#id_city');
        $.ajax({
          url: 'https://secure.geonames.org/searchJSON?q=' + stateNameFirstWord + '&username=juliia55&style=FULL&fclName=city, village,...&maxRows=1000',
          type: 'GET',
          dataType: 'json',
          success: function (data) {
            city.html('<option value="" selected disabled>Select City</option>');
            $.each(data.geonames, function (key, value) {
              city.append('<option value="' + value.name + '">' + value.name + '</option>');
            });
          }
        });
      });
      $(function () {
        $("#id_is_primary").checkboxradio();
      });
    });
  </script>
{% endblock %}

profiles/templates/profiles/edit_address.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Edit Address{% endblock %}

{% block content %}
  <div class="profile">
    <div class="profile__section">
      <div class="">
        <form class="dashboard__form address__form" method="post">
          <h1>Edit Address</h1>
          {% csrf_token %}
          {{ address_form.as_p }}
          <div class="form__btns accent">
            <a href="{% url 'my_addresses' user=request.user %}" aria-label="Go to addresses details"
              class="btn btn-primary btn__cancel">
              <i class="fas fa-arrow-circle-left"></i>
              Cancel
            </a>
            <button class="btn btn__save" id="save-address-btn" type="submit">
              <i class="fas fa-save"></i>
              Save
            </button>
          </div>
        </form>
      </div>
    </div>
    {% comment %} Delete Address Form {% endcomment %}
    <div class="address__delete--form">
      <button class="btn__delete btn" id="btn-delete-address">
        <i class="fas fa-trash-alt"></i>
        Delete Address
      </button>
      <div class="address__delete--dropdown hidden" id="delete-dropwdown">
        <p>Are you sure you want to permanently delete this address?</p>
        <p>This action is irreversible!</p>
        <div class="btn__container">
          <a id="delete-confirm" href="{% url 'delete_address' user=request.user.username pk=address.pk %}"
            class="btn btn__delete">
            <i class="fas fa-trash-alt"></i>
            Yes, delete this Address
          </a>
          <a id="delete-cancel" href="javascript:void(0);" class="btn btn__cancel btn-primary">
            <i class="fas fa-times"></i>
            No, cancel
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block postloadjs_extra %}
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function () {
      let user_country = '{{ address.country }}';
      let user_county_region = '{{ address.county_region }}';
      let user_city = '{{ address.city }}';
      $('#id_country').select2(
        {
          placeholder: "Select a country",
          allowClear: true,
        }
      );
      $('#id_county_region').select2(
        {
          placeholder: "Select a county or region",
          allowClear: true,
        }
      );
      $('#id_city').select2(
        {
          placeholder: "Select a city",
          allowClear: true,
        }
      );
      $('#id_country').on('select2:open', function () {
        $('body').css('overflow-x', 'hidden');
      });
      $('#id_city').on('select2:open', function () {
        $('body').css('overflow-x', 'hidden');
      });
      $('#id_county_region').on('select2:open', function () {
        $('body').css('overflow-x', 'hidden');
      });
      $('#id_country').on('select2:close', function () {
        $('body').css('overflow-x', 'auto');
      });
      $('#id_county_region').on('select2:close', function () {
        $('body').css('overflow-x', 'auto');
      });
      $('#id_city').on('select2:close', function () {
        $('body').css('overflow-x', 'auto');
      });
      // need to fetch only country names from geonames.org
      $.ajax({
        url: 'https://secure.geonames.org/countryInfoJSON?username=juliia55',
        type: 'GET',
        dataType: 'json',
        success: function (data) {
          let select = $('#id_country');
          for (var i = 0; i < data.geonames.length; i++) {
            select.append($('<option>', {
              value: data.geonames[i].countryName,
              text: data.geonames[i].countryName,
              data: {
                code: data.geonames[i].countryCode,
                id: data.geonames[i].geonameId,
              }
            }));
          }
          $('#id_country').val(user_country).trigger('change');
        }
      });
      $('#id_country').on('change', () => {
        let countryId = $('#id_country').find(':selected').data('id');
        $.ajax({
          url: 'https://secure.geonames.org/childrenJSON?geonameId=' + countryId + '&username=juliia55',
          type: 'GET',
          dataType: 'json',
          success: function (data) {
            let select = $('#id_county_region');
            select.empty();
            select.append($('<option>', {
              value: '',
              text: 'Select a county or region',
              data: {
                code: '',
                id: '',
              }
            }));
            for (var i = 0; i < data.geonames.length; i++) {
              select.append($('<option>', {
                value: data.geonames[i].name,
                text: data.geonames[i].name,
                data: {
                  code: data.geonames[i].countryCode,
                  id: data.geonames[i].geonameId,
                }
              }));
            }
            // select user's county or region by default
            $('#id_county_region').val(user_county_region).trigger('change');
          }
        });
      });
      $('#id_county_region').on('change', () => {
        let stateName = $('#id_county_region').find(':selected').text();
        let stateNameFirstWord = stateName.split(' ')[0];
        const city = $('#id_city');
        $.ajax({
          url: 'https://secure.geonames.org/searchJSON?q=' + stateNameFirstWord + '&username=juliia55&style=FULL&fclName=city, village,...&maxRows=1000',
          type: 'GET',
          dataType: 'json',
          success: function (data) {
            city.html('<option value="" selected disabled>Select City</option>');
            $.each(data.geonames, function (key, value) {
              city.append('<option value="' + value.name + '">' + value.name + '</option>');
            });
            $('#id_city').val(user_city);
          }
        });
      });
      $(function () {
        $("#id_is_primary").checkboxradio();
      });

      $('#btn-delete-address').on('click', (e) => {
        $('#delete-dropwdown').toggleClass('hidden');
        $('html, body').animate({
          scrollTop: $(document).height()
        }, 'slow');
      });
      $('#delete-cancel').on('click', (e) => {
        $('#delete-dropwdown').addClass('hidden');
      });
    });
  </script>
{% endblock %}

profiles/templates/profiles/my_addresses.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <style>

  </style>
{% endblock %}

{% comment %} Extra Title {% endcomment %}
{% block extra_title %}Addresses{% endblock %}

{% block content %}
  <div class="profile">
    <h1>Your addresses:</h1>
    <div>
      <a href="{% url 'add_address' user=request.user %}" class="btn btn__add">
        <i class="fas fa-plus-circle"></i>
        Add new address
      </a>
    </div>
    <div class="addresses__all">
      {% if addresses %}
        {% for address in addresses %}
          {% if address.is_primary %}
            <div class="address__card address__card--primary">
              <div class="address__card--data">
                <div>
                  <strong>Country: </strong>{{ address.country }}
                </div>
                <div>
                  <strong>Region: </strong>{{ address.county_region }}
                </div>
                <div>
                  <strong>City: </strong>{{ address.city }}
                </div>
                <div>
                  <strong>Address Line: </strong>{{ address.address_line }}
                </div>
                <div>
                  <strong>Zip code: </strong>{{ address.zip_code }}
                </div>
                <div>
                  <strong>Phone: </strong>{{ address.phone_number }}
                </div>
                <div>
                  <strong>Primary: </strong>{{ address.is_primary }}
                </div>
              </div>
              <div class="address__card--btns">
                <a class="address__card--edit" href="{% url 'edit_address' user=request.user pk=address.pk %}"
                  aria-label="Go to Edit Address Page">
                  Edit
                  <i class="fas fa-edit"></i>
                </a>
                <a class="address__primary--btn address__card--disable" aria-label="Disable Primary Address"
                  data-id="{{ address.id }}">
                  Disable as Primary
                </a>
              </div>
            </div>
          {% else %}
            <div class="address__card">
              <div class="address__card--data">
                <div>
                  <strong>Country: </strong>{{ address.country }}
                </div>
                <div>
                  <strong>Region: </strong>{{ address.county_region }}
                </div>
                <div>
                  <strong>City: </strong>{{ address.city }}
                </div>
                <div>
                  <strong>Address Line: </strong>{{ address.address_line }}
                </div>
                <div>
                  <strong>Zip code: </strong>{{ address.zip_code }}
                </div>
                <div>
                  <strong>Phone: </strong>{{ address.phone_number }}
                </div>
                <div>
                  <strong>Primary: </strong>{{ address.is_primary }}
                </div>
              </div>
              <div class="address__card--btns">
                <a class="address__card--edit" href="{% url 'edit_address' user=request.user pk=address.pk %}"
                  aria-label="Go to Edit Address Page">
                  Edit
                  <i class="fas fa-edit"></i>
                </a>
                <a class="address__primary--btn address__card--enable" aria-label="Enable Primary Address"
                  data-id="{{ address.pk }}">
                  <div>Enable as Primary</div>
                </a>
              </div>
            </div>
          {% endif %}
        {% endfor %}
      {% else %}
        <p>You have no addresses.</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block postloadjs_extra %}
  <script>
    $(document).ready(function () {
      let disableAddress = document.querySelector('.address__card--disable');
      $('.address__primary--btn').each(function (address) {
        $(this).on('click', function (e) {
          e.preventDefault();
          let addressId = $(this).data('id');
          $(this).html('');
          $(this).append('<i class="fas fa-spinner fa-spin"></i>');
          $.ajax({
            url: "{% url 'set_primary_address' %}",
            type: 'POST',
            data: {
              'address_id': addressId,
              'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function (data) {
              // reset all other addresses to not primary
              $('.address__card').each(function (address) {
                $(this).removeClass('address__card--primary');
              });
              $('.address__primary--btn').each(function (address) {
                $(this).removeClass('address__card--disable');
                $(this).addClass('address__card--enable');
                $(this).text('Enable as Primary');
                //add href
                $(this).attr('href', 'Enable primary address');
              });
              $('.fa-spinner').remove();
              if (data.primary) {
                let cardParent = $('[data-id="' + addressId + '"]').parent().parent();
                cardParent.addClass('address__card--primary');
                $('[data-id="' + addressId + '"]').removeClass('address__card--enable');
                $('[data-id="' + addressId + '"]').addClass('address__card--disable');
                $('[data-id="' + addressId + '"]').text('Disable as Primary');
                $('[data-id="' + addressId + '"]').attr('href', 'Disable primary address');
              }
              setTimeout(() => {
                $('.success-message').remove();
              }, 3000);
            },
            error: function (data) {
              $('.fa-spinner').remove();
              $('#messages-notes').remove();
              $('.profile').before('<div class="message-container" id="messages-notes">' +
                '<div class="message-container__message">' +
                '<p class="message-container__message--text">Something went wrong</p>' +
                '</div>' +
                '</div>');
              setTimeout(() => {
                $('#messages-notes').remove();
              }, 3000);
            }
          });
        });
      });
    });
  </script>
{% endblock %}